//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEverything.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRankForModule
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PID { get; set; }
        public string StudentNumber { get; set; }
        public string Class { get; set; }
        public string Grade { get; set; }
        public string School { get; set; }
        public string District { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<int> RankInClass { get; set; }
        public Nullable<int> RankInSchool { get; set; }
        public Nullable<int> RankInDistrict { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
